### PR TITLE
Pallier py3

### PR DESCRIPTION
**Pull request by chrplr**
An attempt to write a  Python 3 version.

To convert from Python 2, I mostly had to:

- add parentheses to calls to `print`
- replace some `/`' by `//` (integer division)
- remove `from string import split` and replace calls to `split` by calls to `str.split`

TODO;
- In meica.py I commented out the code writing a call to `nifti_tool` because it creates a problem on my machine. I have to understand what is going on there.

### CODE REVIEW

**Comment by emdupre** [comment]
Thanks so much, @chrplr ! There's too much code to review here, but I imagine this was assisted with something like [futurize](http://python-future.org/futurize.html) ? So long as you're able to get this code working on your machine, I'll take that as a very strong suggestion that this was a successful conversion.

Just to let you know, we're most active development is taking place on the [tedana](https://github.com/me-ica/tedana) repository-- the hope is that code base will replace ME-ICA. We'd love to have your efforts there !

Please do let me know if you plan to continue testing this code and are able to get `nifti_tool` working for you.

**Comment by chrplr** [comment]
Ah! I did not know about futurize :-(
I used 2to3 as a first pass, then manually corrected the incompatibilities I found running the program (there are not so many, if many lines were changed it could be just due to reformatting). 

This is a work in progress, incomplete, and unfortunately not compatible with python2 (it was more of a quick fix to make meica run with python3). But I'd be happy to start again and make a cleaner conversion.

**Comment by chrplr** [comment]
Just for information : 
For information:

I encountered many crashes with meica Version 3.2 beta1 (python 2.7) but they were due to the verison of afni that was installed on my computer (Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1) from neurodebian).
After installing a more recent version of afni from the afni web site (AFNI_18.2.06 (Jul 31 2018)), meica.py runs well.

**Comment by emdupre** [comment]
Thanks again for contributing this !

Unfortunately, since I'm going to archive this repository, I don't think it makes sense to consider merging it. Instead, I'm closing this PR. If you have time and interest in the future, we'd appreciate your contributions on [the tedana repository](https://github.com/me-ica/tedana) !

**Pull request closed without merging**
